workflows:
  android-assemble:
    name: Teclo Build
    scripts:
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          gradle wrapper
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
